Sort list of sorted integer lists
relentlessmaverick/AlgorithmsStudy pull request #4
Opened 2020-08-16 01:39 UTC by rclin

**Problem:** 
Sort list of sorted integer lists

**Solution**
Put all integers into one array and sort it

T(N) = O(kNlogkN) where k = # of lists, and N = max size of list
kNlogKN is the time complexity for quicksort, which is used under-the-hood by Arrays.sort() for primitives sorting.

S(N) = O(kN)
Space is allocated for all elements before sorting

2020-08-24 05:54 UTC, relentlessmaverick approved these changes

2020-08-24 05:54 UTC, relentlessmaverick approved these changes

2020-08-24 05:54 UTC, relentlessmaverick approved these changes

2020-08-24 05:57 UTC, relentlessmaverick requested changes
You could have used Collections.sort(listToSort). Isn't it ?
Converting from list to array & again from array to list (when you return back) is an overhead

2020-08-25 03:05 UTC, rclin commented
> You could have used Collections.sort(listToSort). Isn't it ?
> Converting from list to array & again from array to list (when you return back) is an overhead

I think there is no extra overhead.  Although Collections.sort() takes in a list, eventually that list needs to be converted to an array for the quicksort or mergesort algorithms.

It would definitely look cleaner using Collections.sort() though.

2020-08-25 04:56 UTC, relentlessmaverick approved these changes

2020-08-25 05:04 UTC, relentlessmaverick approved these changes

2020-08-25 05:05 UTC, merged